
project_id = "aebuzslludwlpcbdpljx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions]
[functions.advanced-analysis]
verify_jwt = true
[functions.gpt-chat]
verify_jwt = true
