
project_id = "aebuzslludwlpcbdpljx"

[functions.analyze-idea]
verify_jwt = true

[functions.compare-ideas]
verify_jwt = true

[functions.advanced-analysis]
verify_jwt = true

[functions.gpt-chat]
verify_jwt = true
