
project_id = "aebuzslludwlpcbdpljx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://loving-production.up.railway.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
anonymous_users_enabled = false
enable_signup = true
email_double_confirm_changes_enabled = true

[db]
port = 54322

[storage]
enabled = true
port = 54323

[functions.advanced-analysis]
verify_jwt = true

[functions.analyze-idea]
verify_jwt = true

[functions.compare-ideas]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-business-name]
verify_jwt = true

[functions.generate-business-model-canvas]
verify_jwt = true

[functions.generate-business-plan]
verify_jwt = true

[functions.generate-cac-ltv]
verify_jwt = true

[functions.generate-color-palette]
verify_jwt = true

[functions.generate-competitor-analysis]
verify_jwt = true

[functions.generate-content-marketing]
verify_jwt = true

[functions.generate-daily-insights]
verify_jwt = true

[functions.generate-financial-analysis]
verify_jwt = true

[functions.generate-investment-simulator]
verify_jwt = true

[functions.generate-landing-page]
verify_jwt = true

[functions.generate-logo]
verify_jwt = true

[functions.generate-market-analysis]
verify_jwt = true

[functions.generate-market-timing]
verify_jwt = true

[functions.generate-marketing-strategy]
verify_jwt = true

[functions.generate-pitch-deck]
verify_jwt = true

[functions.generate-post-generator]
verify_jwt = true

[functions.generate-prd-mvp]
verify_jwt = true

[functions.generate-pricing-model]
verify_jwt = true

[functions.generate-process-automation]
verify_jwt = true

[functions.generate-ai-image-editor]
verify_jwt = true

[functions.generate-report-creator]
verify_jwt = true

[functions.generate-invoice-generator]
verify_jwt = true

[functions.generate-revenue-forecast]
verify_jwt = true

[functions.generate-roadmap]
verify_jwt = true

[functions.generate-seo-analysis]
verify_jwt = true

[functions.generate-social-media-planner]
verify_jwt = true

[functions.generate-startup-kit]
verify_jwt = true

[functions.generate-trend-analysis]
verify_jwt = true

[functions.generate-user-research]
verify_jwt = true

[functions.generate-valuation-calculator]
verify_jwt = true

[functions.gpt-chat]
verify_jwt = true

[functions.industry-benchmarks]
verify_jwt = true

[functions.match-adopters]
verify_jwt = true

[functions.regulatory-analysis]
verify_jwt = true

[functions.scenario-simulator]
verify_jwt = true

[functions.sector-analysis]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

