
project_id = "aebuzslludwlpcbdpljx"

[api]
enabled = true
port = 54321
schemas = []

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[functions.gpt-chat]
verify_jwt = true

[functions.advanced-analysis]
verify_jwt = true

