
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aebuzslludwlpcbdpljx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYnV6c2xsdWR3bHBjYmRwbGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDc3MDQsImV4cCI6MjA2MjAyMzcwNH0.YOizGdrHWDlPuDMcwDklrVIkOuyByVMzj3y_wvG5dtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
